"""empty message

Revision ID: 000d1e48894e
Revises: 79636200a39a
Create Date: 2026-04-03 11:14:38.054453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000d1e48894e'
down_revision: Union[str, Sequence[str], None] = '79636200a39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
