"""empty message

Revision ID: 1d3f04fd7fb2
Revises: 538f3fbb0feb
Create Date: 2026-04-03 10:48:23.218022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3f04fd7fb2'
down_revision: Union[str, Sequence[str], None] = '538f3fbb0feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'phone_number')
    # ### end Alembic commands ###
