"""empty message

Revision ID: 57791ab9c2b3
Revises: 8b2b75e5b1d2
Create Date: 2026-04-03 11:00:59.001556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57791ab9c2b3'
down_revision: Union[str, Sequence[str], None] = '8b2b75e5b1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'phone_number')
    # ### end Alembic commands ###
