"""empty message

Revision ID: 8b2b75e5b1d2
Revises: 1d3f04fd7fb2
Create Date: 2026-04-03 10:48:50.279690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2b75e5b1d2'
down_revision: Union[str, Sequence[str], None] = '1d3f04fd7fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
